version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install pm2
  pre_build:
    commands:
  build:
    commands:
      - npm run build
  post_build:
    commands:
artifacts:
  files:
    - "**/*"
  discard-paths: no